# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/katherinelu/Documents/15418/kat-04.github.io

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/katherinelu/Documents/15418/kat-04.github.io

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/katherinelu/Documents/15418/kat-04.github.io/CMakeFiles /Users/katherinelu/Documents/15418/kat-04.github.io//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/katherinelu/Documents/15418/kat-04.github.io/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GOL3D

# Build rule for target.
GOL3D: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GOL3D
.PHONY : GOL3D

# fast build rule for target.
GOL3D/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GOL3D.dir/build.make CMakeFiles/GOL3D.dir/build
.PHONY : GOL3D/fast

src/gol-sequential.o: src/gol-sequential.cpp.o
.PHONY : src/gol-sequential.o

# target to build an object file
src/gol-sequential.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GOL3D.dir/build.make CMakeFiles/GOL3D.dir/src/gol-sequential.cpp.o
.PHONY : src/gol-sequential.cpp.o

src/gol-sequential.i: src/gol-sequential.cpp.i
.PHONY : src/gol-sequential.i

# target to preprocess a source file
src/gol-sequential.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GOL3D.dir/build.make CMakeFiles/GOL3D.dir/src/gol-sequential.cpp.i
.PHONY : src/gol-sequential.cpp.i

src/gol-sequential.s: src/gol-sequential.cpp.s
.PHONY : src/gol-sequential.s

# target to generate assembly for a file
src/gol-sequential.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GOL3D.dir/build.make CMakeFiles/GOL3D.dir/src/gol-sequential.cpp.s
.PHONY : src/gol-sequential.cpp.s

src/main-local.o: src/main-local.cpp.o
.PHONY : src/main-local.o

# target to build an object file
src/main-local.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GOL3D.dir/build.make CMakeFiles/GOL3D.dir/src/main-local.cpp.o
.PHONY : src/main-local.cpp.o

src/main-local.i: src/main-local.cpp.i
.PHONY : src/main-local.i

# target to preprocess a source file
src/main-local.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GOL3D.dir/build.make CMakeFiles/GOL3D.dir/src/main-local.cpp.i
.PHONY : src/main-local.cpp.i

src/main-local.s: src/main-local.cpp.s
.PHONY : src/main-local.s

# target to generate assembly for a file
src/main-local.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GOL3D.dir/build.make CMakeFiles/GOL3D.dir/src/main-local.cpp.s
.PHONY : src/main-local.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GOL3D"
	@echo "... src/gol-sequential.o"
	@echo "... src/gol-sequential.i"
	@echo "... src/gol-sequential.s"
	@echo "... src/main-local.o"
	@echo "... src/main-local.i"
	@echo "... src/main-local.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

